CREATE TABLE IF NOT EXISTS `#__road_fare_bill_helper_customers` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `customer_code` varchar(64) NOT NULL,
  `customer_name` varchar(255) NOT NULL DEFAULT '',
  `customer_address` varchar(512) NOT NULL DEFAULT '',
  `vat_id` varchar(64) NOT NULL DEFAULT '',
  `outside_country` varchar(16) NOT NULL DEFAULT '',
  `custom_country_name` varchar(255) NOT NULL DEFAULT '',
  `outside_vat_rate` decimal(10,4) NOT NULL DEFAULT 0,
  `outside_revenue_account` varchar(32) NOT NULL DEFAULT '',
  `custom_invoice_message` text NULL,
  `created_by` int unsigned NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_customer_code` (`customer_code`),
  KEY `idx_created_by` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__road_fare_bill_helper_invoices` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `customer_id` int unsigned NOT NULL,
  `customer_code` varchar(64) NOT NULL,
  `customer_name` varchar(255) NOT NULL DEFAULT '',
  `customer_address` varchar(512) NOT NULL DEFAULT '',
  `vat_id` varchar(64) NOT NULL DEFAULT '',
  `invoice_number` varchar(64) NOT NULL,
  `output_file_name` varchar(255) NOT NULL DEFAULT '',
  `pickup` varchar(255) NOT NULL DEFAULT '',
  `dropoff` varchar(255) NOT NULL DEFAULT '',
  `total_km` decimal(12,4) NOT NULL DEFAULT 0,
  `slovenia_km` decimal(12,4) NOT NULL DEFAULT 0,
  `outside_slovenia_km` decimal(12,4) NOT NULL DEFAULT 0,
  `taxable_base_slovenia` decimal(12,4) NOT NULL DEFAULT 0,
  `outside_slovenia_base` decimal(12,4) NOT NULL DEFAULT 0,
  `vat_rate` decimal(10,4) NOT NULL DEFAULT 0,
  `vat_amount` decimal(12,4) NOT NULL DEFAULT 0,
  `outside_vat_rate` decimal(10,4) NOT NULL DEFAULT 0,
  `outside_vat_amount` decimal(12,4) NOT NULL DEFAULT 0,
  `total_amount` decimal(12,4) NOT NULL DEFAULT 0,
  `payload_json` mediumtext NULL,
  `created_by` int unsigned NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_invoice_number` (`invoice_number`),
  KEY `idx_customer_id` (`customer_id`),
  KEY `idx_customer_code` (`customer_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
