CREATE TABLE IF NOT EXISTS `#__route_calculation_help_for_accounting_invoices` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `customer_id` int unsigned NOT NULL,
  `customer_code` varchar(64) NOT NULL,
  `customer_name` varchar(255) NOT NULL DEFAULT '',
  `customer_address` varchar(512) NOT NULL DEFAULT '',
  `vat_id` varchar(64) NOT NULL DEFAULT '',
  `invoice_number` varchar(64) NOT NULL,
  `document_type` varchar(16) NOT NULL DEFAULT 'invoice',
  `document_status` varchar(16) NOT NULL DEFAULT 'issued',
  `source_document_id` int unsigned NULL DEFAULT NULL,
  `converted_invoice_id` int unsigned NULL DEFAULT NULL,
  `converted_invoice_number` varchar(64) NOT NULL DEFAULT '',
  `output_file_name` varchar(255) NOT NULL DEFAULT '',
  `pickup` varchar(255) NOT NULL DEFAULT '',
  `dropoff` varchar(255) NOT NULL DEFAULT '',
  `total_km` decimal(12,4) NOT NULL DEFAULT 0,
  `slovenia_km` decimal(12,4) NOT NULL DEFAULT 0,
  `outside_slovenia_km` decimal(12,4) NOT NULL DEFAULT 0,
  `taxable_base_slovenia` decimal(12,4) NOT NULL DEFAULT 0,
  `outside_slovenia_base` decimal(12,4) NOT NULL DEFAULT 0,
  `vat_rate` decimal(10,4) NOT NULL DEFAULT 0,
  `vat_amount` decimal(12,4) NOT NULL DEFAULT 0,
  `outside_vat_rate` decimal(10,4) NOT NULL DEFAULT 0,
  `outside_vat_amount` decimal(12,4) NOT NULL DEFAULT 0,
  `total_amount` decimal(12,4) NOT NULL DEFAULT 0,
  `payload_json` mediumtext NULL,
  `created_by` int unsigned NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_invoice_number` (`invoice_number`),
  UNIQUE KEY `idx_source_document_id` (`source_document_id`),
  KEY `idx_document_type_status` (`document_type`, `document_status`),
  KEY `idx_customer_id` (`customer_id`),
  KEY `idx_customer_code` (`customer_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
